#!/bin/sh

battery_status()
{
  ioreg -c AppleSmartBattery -w0 | \
    grep -o '"[^"]*" = [^ ]*' | \
    sed -e 's/= //g' -e 's/"//g' | \
    sort | \
    while read key value; do
      case $key in
        "MaxCapacity")
          export maxcap=$value;;
        "CurrentCapacity")
          export curcap=$value;;
        "ExternalConnected")
          export extconn="${value}"
          if [ "$value" = "No" ]; then
            export extconn="-"
          else
            export extconn="+"
          fi
          ;;
        "FullyCharged")
          if [ "$value" = "Yes" ]; then
            exit
          fi
          ;;
      esac
      if [[ -n "$maxcap" && -n $curcap ]]; then
        echo "${extconn}"$(( 100 * $curcap / $maxcap ))
        break
      fi
    done
}

BATTERY_STATUS=`battery_status`
[ -z "$BATTERY_STATUS" ] && exit

echo ${BATTERY_STATUS}%
