#!/bin/bash

line=''
line=$line'#(date +"%I:%M %p") ' \
line=$line'#[fg=colour238,nobold]'
line=$line'#[fg=colour254, bg=colour238]'
line=$line' #(date +"%D %a") '
line=$line' #(tmux-spotify-info) '
#line=$line'#[fg=colour254,nobold]'
#line=$line'#[fg=colour16,bg=colour254,bold]'
#line=$line' --- '
line=$line'#(rainbarf --width 20 --battery --remaining --bolt --tmux --rgb)'

echo $line

